# Generated by Django 3.2.11 on 2022-01-16 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('img', models.ImageField(default='uploads\\product-1.jpg', upload_to=shop.models.get_image_path)),
                ('on_sale', models.BooleanField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('percent_off', models.DecimalField(blank=True, decimal_places=1, max_digits=30, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True)),
                ('bought_counter', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
